seconomy:
  #Gibt an wo das root-Verzeichnis vom Plugin ist. Ist ueberholt und wird in neueren Versionen entfernt.
  root: ./plugins/SEconomy
  
  #Verwendete Sprache
  language: german
  
  #Startwert beim erstellen eines Accounts
  startvalue: 100
  #Standard limit.
  limit: -50
  
  #Steuern die beim einzahlen an das adminkonto gesendet werden.
  tax: 10
  
  cleanquantity: 1
  cleantype: month
  cleaninginterval: 2000000
  autocleaning: false
  
  username: root
  password: admin
  hostname: localhost
  port: 3306
  database: default
  
  #Spieler, die aus der money top gefiltert werden
  topfilter: []